### ISSUE TITLE
Implement vsqrl

### ISSUE THREAD

**Issue by toelli-msft** [microsoft/knossos-ksc#966]
@awf @cgravill: I get the impression that `sqrl` is like "pooling operation" so we want `vsqrl` that takes a tensor of size 4mx4n and applies `sqrl` to 4x4 subtensors (with a stride of 4x4). Is that right?

https://github.com/microsoft/knossos-ksc/blob/88e1491849f10893cb97e04281835477d6a19c9b/examples/dl-capsule/sqrl.py#L5-L17

**Comment by awf** [comment]
closed by #1019
